Feat/research files
xi-effect/xi.front pull request #126
Opened 2022-08-30 21:05 UTC by s2000promax

2022-09-05 20:51 UTC, s2000promax commented
Согласно задачам:
https://www.notion.so/xieffect/550cdba77da143479b4461eb41f3957d
https://www.notion.so/xieffect/FileUpload-99898c8650ed4a7396bb27e89c7d1392

1. По адресу http://localhost:3000/research открывается временный "стенд" для тестирования загрузки файлов. 
"Стенд" не привязан к дизайн-макету, только лишь моделирует некоторые поведения при отаравке файлов на сервер.
Исходный код "стенда" расположен в папке /pages/research/ingex.jsx. Не нуждается в ревью, может быть доработам, модернизирован согласно любым условиям задачи исследования загрузки файлов.

2. Для загрузки, выгрузки и удаления файлов с сервера, был разработам кастомный хук - /kit/useFetcher.ts.
Хук разбит на три метода: 
- useGetFetcher - получение файлов с сервера.
- usePostFetcher - загрузки файлов на сервер.
- useDeleteFetcher - удаления файла с сервера.

Все три метода имеют схожий алгоритм работы:
1.уcтанавливается флаг загрузки isLoading в состояние true
2. просходит попытка работы с сервером (get, post или delete)
3. в случае успешного ответа или подтверждения сервера, в случае с get-запросом, пользователю приходит запрашиваемое изображение, в случае с post или delet - консольное подтверждение
4. в случает ошибки, в том числе по обрыву связи, пользователю прийдет соответсвуюшее сообщение в переменной errors
5. cтанавливается флаг загрузки isLoading в состояние false

Методы имеют встроенную валидацию на проверку: пустых имен, пустых идентификаторов, предупреждение о превышении максимально возможного размера файла.

2022-09-05 21:18 UTC, niqzart reviewed
А так норм, я ток про future-proof тут написал кучу

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +  const [errors, setErrors] = useState<string>();
Чтобы сделать эту вещь более переиспользуемой, можно отделить state-ы от хука, а проще, сделать доступной отдельно функцию handleGet (ну + переименовать получше). Функция handleGet может спокойно быть простой функцией, что возвращает пару значений, например:
```ts
interface GetResult {
  url?: string,
  error?: string,
}
```
А сам useGetFetcher уже будет создавать стейты и использовать эту функцию

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +import { useState } from 'react';
По названиям: 

useFetcher - плохо. Мы же про файлы, так это нужно отразить в названии, хотя бы useFileFetcher, а может и просто useFiles какое

useGetFetcher - на useFileGetter или useFileUploader, например

и т.п.

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +  const [errors, setErrors] = useState<string>();
Имя для функции, наверное, getFile или downloadFile

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +const baseUrl: string = 'https://xieffect.ru:5000/files/';
Использовать serverURL из окружения, не сырое `https://xieffect.ru:5000/`!

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +        setErrors('Размер файла превышает 4 МБ');
А лимит 4 MiB, `4 * 1024 ** 2`, но это детали, можно не править))

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +  const [errors, setErrors] = useState<string>();
Тоже самое про выделение функций можно к загрузке и удалению отнести

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +      }
switch на две ветки это перебор...

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +          throw new Error('Ошибка удаления файла');
опять же, если переделать на функцию, тут будет return, а не долгое throw

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +    while (filesToPost.length) {
Лучше сделать хук или функцию на 1 файл и вызывать её в цикле в другом хуке или функции, условно:
```ts
function postFile(file: IFile) {}
function postFiles(files: IFile[]) {
  for (const file of filesToPost) postFile;
}
```

2022-09-05 21:18 UTC, niqzart commented on kit/useFetcher.ts
> +            // eslint-disable-next-line no-await-in-loop,no-case-declarations
Линтер не просто так на это ругается))

2022-09-05 21:20 UTC, niqzart commented on kit/useFetcher.ts
> +  const [errors, setErrors] = useState<string>();
(isLoading тоже вне функции)

2022-09-06 20:36 UTC, unknownproperty reviewed
Не сказать, что я много чего тут ещё нашёл

2022-09-06 20:36 UTC, unknownproperty commented on kit/useFetcher.ts
> +const baseUrl: string = 'https://xieffect.ru:5000/files/';
Да, было бы славно

2022-09-08 13:30 UTC, s2000promax commented
После рефакторинга:

Согласно задачам:
https://www.notion.so/xieffect/550cdba77da143479b4461eb41f3957d
https://www.notion.so/xieffect/FileUpload-99898c8650ed4a7396bb27e89c7d1392

По адресу http://localhost:3000/research открывается временный "стенд" для тестирования загрузки файлов.
"Стенд" не привязан к дизайн-макету, только лишь моделирует некоторые поведения при отправке файлов на сервер.
Исходный код "стенда" расположен в папке /pages/research/index.jsx. Не нуждается в ревью, может быть доработан, модернизирован согласно любым условиям задачи исследования загрузки файлов.

Для загрузки, выгрузки и удаления файлов с сервера, был разработан кастомный хук - /utils/useFiles.ts.
Хук разбит на три метода:

useGetFiles - получение файлов с сервера.
usePostFiles - загрузки файлов на сервер.
useDeletetFiles - удаления файла с сервера.
Все три метода имеют схожий алгоритм работы:
1.уcтанавливается флаг загрузки isLoading (isUploading, isDeleting) в состояние true
2. просходит попытка работы с сервером (get, post или delete)
3. в случае успешного ответа или подтверждения сервера, в случае с get-запросом, пользователю приходит запрашиваемое изображение, в случае с post или delete - консольное подтверждение
4. в случает ошибки, в том числе по обрыву связи, пользователю прийдет соответсвуюшее сообщение в переменной errors. А в случае с post-запросом - пользователь обратно получит файлы, которые не загрузились на сервер.
5. cтанавливается флаг загрузки isLoading в состояние false

Методы имеют встроенную валидацию на проверку: пустых имен, пустых идентификаторов, предупреждение о превышении максимально возможного размера файла.

2022-09-08 13:40 UTC, s2000promax commented on utils/useFiles.ts
> +const baseUrl: string = `${process.env.NEXT_PUBLIC_SERVER_URL}/files/`;
baseUrl - вытащил из process.env

2022-09-08 13:40 UTC, s2000promax commented on utils/useFiles.ts
> +};
использовал функции для getFile, postFile и deleteFile

2022-09-08 13:40 UTC, s2000promax commented on utils/useFiles.ts
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
isLoading оставил внутри хука, но тоже хочется сделать один и переиспользовать для всех трёх методов

2022-09-08 13:40 UTC, s2000promax commented on utils/useFiles.ts
> +        return false;
изначально умножал на 1024, но заметил. что "проводник" отображает размер нев Mib, а в Мб и чтобы не вводить в заблуждение дотошных пользователей - оставил 1000.

2022-09-08 13:40 UTC, s2000promax commented on utils/useFiles.ts
> +  };
вместо while решил реалт-овать с рекурсией

2022-09-10 09:55 UTC, unknownproperty requested changes
Сделал финальное ревью. Предлагаю замержить в pre-main, но оставить ветку для тестов

2022-09-10 09:55 UTC, unknownproperty commented on utils/useFiles.ts
> +      // console.log(data);
Консольку забыл

2022-09-10 09:55 UTC, unknownproperty commented on utils/useFiles.ts
> +    // console.log(data);
И здесь консолька. Я понимаю, что она потом будет использоваться для тестирования и т.д. Но мы же всё же за чистый код

2022-09-10 13:45 UTC, niqzart commented on utils/useFiles.ts
> +        return false;
Так эта функция же проверяет максимальный размер, а не выводит размер пользователю, то как проводник это выводит не при делах. Я просто к тому, что сервер разрешает 4 MiB, а сайт - только 4 MB... Но это вообще не особо важно, 413 не будет и норм

2022-10-09 17:53 UTC, merged

2022-10-09 17:53 UTC, unknownproperty commented
Замержил, но закрывать не буду, чтоб потом можно было вернуться